export const ui = {
    SHOW_LOADER: 'UI:SHOW_LOADER',
    HIDE_LOADER: 'UI:HIDE_LOADER',

    SHOW_TOASTER: 'UI:SHOW_TOASTER',
    HIDE_TOASTER: 'UI:HIDE_TOASTER',

    SHOW_MODAL: 'UI:SHOW_MODAL',
    HIDE_MODAL: 'UI:HIDE_MODAL',
    
    SHOW_HEADER: 'UI:SHOW_HEADER',
    HIDE_HEADER: 'UI:HIDE_HEADER',
    
    LOADING: 'UI:LOADING',
    LOADED: 'UI:LOADED'
};

export const user = {
    AUTH: 'USER:AUTH',
    
    LOGIN: 'USER:LOGIN',
    LOGOUT: 'USER:LOGOUT',
    
    SET_META: 'USER:SET_META',
    DELETE_META: 'USER:DELETE_META'
}